tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'

brew 'autojump'
brew 'jpeg'
brew 'exiftool'
brew 'git'
brew 'openssl'
brew 'gcc'
brew 'git-flow'
brew 'postgresql'
brew 'go'
brew 'httpie'
# brew 'imagemagick'
# brew 'ldid'
brew 'libyaml'
brew 'mitmproxy'
# brew 'mongodb'
# brew 'redis'
# brew 'sqlite'
brew 'ssh-copy-id'
brew 'swiftlint'
# brew 'the_silver_searcher'
# brew 'thefuck'
# brew 'tree'
brew 'wget'
brew 'youtube-dl'
# brew 'tmux'
# brew 'reattach-to-user-namespace'
brew 'diff-so-fancy'