# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.zsh
export LANG=en_US.UTF-8
export NLS_LANG=AMERICAN_AMERICA.UTF8
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow'

ZSH_THEME="miloshadzic"

plugins=(zsh-autosuggestions autojump jump last-working-dir osx sudo xcode docker)

# oh-my-zsh
source $ZSH/oh-my-zsh.sh

# External plugins (initialized before)
source ~/.zsh/plugins_before.zsh
source ~/.zsh/bootstrap.zsh


# -------------

alias reload!='. ~/.zshrc'

# -------------

alias fresh='git checkout master; git pull; git checkout -; git rebase master'

alias masterup='git checkout master; git fa; git pull'

alias ribase='git rebase -i $(git oldest-ancestor)'

# -------------

alias info='find . -iname "*.*" -exec file {} \;'

alias weather='curl wttr.in/Ottawa'

source ~/.zsh/syntax.zsh

