# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.zsh
export LANG=en_US.UTF-8
export NLS_LANG=AMERICAN_AMERICA.UTF8
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow'


ZSH_THEME="miloshadzic"

plugins=(zsh-autosuggestions autojump jump last-working-dir macos sudo xcode docker)


# oh-my-zsh
source $ZSH/oh-my-zsh.sh

# External plugins (initialized before)
source ~/.zsh/plugins_before.zsh
source ~/.zsh/bootstrap.zsh

export PATH=$GOPATH/bin:$PATH
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/bin"
export PATH="$PATH:/bin"
export PATH="$PATH:/usr/sbin"
export PATH="$PATH:/usr/local/sbin"
export PATH="$PATH:/opt/homebrew/bin"

export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`

# -------------

alias reload!='. ~/.zshrc'

# -------------

alias fresh='git checkout main; git pull; git checkout -; git rebase main'

alias masterup='git checkout main; git fa; git pull'

alias ribase='git rebase -i $(git oldest-ancestor)'

# -------------

alias info='find . -iname "*.*" -exec file {} \;'

alias weather='curl wttr.in/Ottawa'

source ~/.zsh/syntax.zsh

